### ISSUE TITLE
How do you add related products to a single woo product?

### ISSUE THREAD

**Issue by Eworm** [hrsetyono/generator-edje#9]
Hi!

I'm working on a timber/woocommerce theme, and the one thing I can't seem to figure out is how to show my own code for a related product. I found this line of code in your woocommerce.php

```$context['related_products'] = get_related_products($product, 3);```

But the get_related_products function doesn't seem to exist. What am I missing?

**Comment by hrsetyono** [comment]
Hi,

It seems you no longer need that snippet since In views/woo/single.twig I called the native Output Related Product function.

Can you try removing that line?

**Comment by Eworm** [comment]
I did, and that works, but my main question would be how to replace the partial code for the related products. Do you know how to do that?

**Comment by hrsetyono** [comment]
One thing I learnt from making Woocommerce site is not to customize the markup too much because it can interfere with many other plugins.

You can see how Woocommerce output the related product by searching the code in woocommerce plugin.

Thanks
